apiVersion: v1
kind: Service
metadata:
  name: commodities-collector
  namespace: market-data
  labels:
    app: commodities-collector
spec:
  selector:
    app: commodities-collector
  ports:
    - name: metrics
      port: 2112
      targetPort: metrics
      protocol: TCP